### ISSUE TITLE
Error in train_cartpole.py

### ISSUE THREAD

**Issue by ghost** [LinZichuan/emdqn#2]
Hello LinZichuan,

  I tried your train_cartpole.py, but got:

 Traceback (most recent call last):
  File "train_cartpole.py", line 31, in <module>
    main()
  File "train_cartpole.py", line 24, in main
    callback=callback
  File "c:\emdqn-master\baselines\deepq\simple.py", line 235, in learn
    td_errors = train(obses_t, actions, rewards, obses_tp1, dones, weights)
  File "c:\emdqn-master\baselines\common\tf_util.py", line 442, in __call__
    assert inpt in self.givens, "Missing argument " + inpt_name
AssertionError: Missing argument qec

       Thanks for your help!

**Comment by LinZichuan** [comment]
> Hello LinZichuan,
> 
> I tried your train_cartpole.py, but got:
> 
> Traceback (most recent call last):
> File "train_cartpole.py", line 31, in 
> main()
> File "train_cartpole.py", line 24, in main
> callback=callback
> File "c:\emdqn-master\baselines\deepq\simple.py", line 235, in learn
> td_errors = train(obses_t, actions, rewards, obses_tp1, dones, weights)
> File "c:\emdqn-master\baselines\common\tf_util.py", line 442, in **call**
> assert inpt in self.givens, "Missing argument " + inpt_name
> AssertionError: Missing argument qec
> 
> ```
>    Thanks for your help!
> ```

Hi, I didn't conduct experiment on cartpole, just on Atari games, and there might be some mismatch code between training atari and training cartpole.
